-- =============================================================================
-- seed.sql
-- Initial seed data for Bottany bot
-- Safe to re-run: ON CONFLICT DO NOTHING throughout
-- =============================================================================

BEGIN;

-- -----------------------------------------------------------------------------
-- anime_awards — 36 verified entries
-- Sources: Oscars, Japan Academy, Annecy, Annie Awards, Mainichi, Fantasia,
--          Sitges, Blue Ribbon, Kinema Junpo, Berlinale, Hiroshima, TAAF
-- -----------------------------------------------------------------------------

-- anime_awards — 36 entries from all_raw.json
-- Generated by anime_awards_to_sql.py

INSERT INTO anime_awards (
  title_en, title_jp, title_display,
  year, era,
  award_show_id, award_name, category, award_type, jp_label,
  directors, studios, productions,
  animation_technique, format,
  thumbnail,
  official_link, imdb_link, mal_link,
  sources, confidence
) VALUES
(
  'Spirited Away','千と千尋の神隠し','Spirited Away | 千と千尋の神隠し',
  2003,'modern',
  'oscars','Academy Awards — Best Animated Feature','Best Animated Feature','feature','賞 (Award)',
  ARRAY['Hayao Miyazaki'],ARRAY['Studio Ghibli'],ARRAY['Tokuma Shoten'],
  'Cel animation / Digital (Mixed)','feature film',
  'https://cdn.bottany.app/anime/spirited_away.jpg',
  'https://www.ghibli.jp/','https://www.imdb.com/title/tt0245429','https://myanimelist.net/anime/199',
  ARRAY['https://awardsdatabase.oscars.org/'],'high'
),
(
  'Akira','アキラ','Akira | アキラ',
  1988,'classic',
  'annecy','Annecy — Screening','Official Selection','screening','賞 (Award)',
  ARRAY['Katsuhiro Otomo'],ARRAY['Tokyo Movie Shinsha'],ARRAY['Akira Committee'],
  'Cel animation','feature film',
  'https://cdn.bottany.app/anime/akira_1988.jpg',
  'https://www.akira2019.com/','https://www.imdb.com/title/tt0094625','https://myanimelist.net/anime/47',
  ARRAY['https://www.annecyfestival.com/'],'medium'
),
(
  'Nausicaä of the Valley of the Wind','風の谷のナウシカ','Nausicaä of the Valley of the Wind | 風の谷のナウシカ',
  1984,'classic',
  'mainichi','Mainichi Film Awards — Ofuji Award','Ofuji Noburo Award','special','大賞 (Grand Prize)',
  ARRAY['Hayao Miyazaki'],ARRAY['Topcraft'],ARRAY['Tokuma Shoten'],
  'Cel animation','feature film',
  'https://cdn.bottany.app/anime/nausicaa.jpg',
  'https://www.ghibli.jp/','https://www.imdb.com/title/tt0087544','https://myanimelist.net/anime/572',
  ARRAY['https://mainichi.jp/'],'high'
),
(
  'Ghost in the Shell','攻殻機動隊','Ghost in the Shell | 攻殻機動隊',
  1995,'classic',
  'sitges','Sitges — Best Animated Film','Best Animated Film','feature','賞 (Award)',
  ARRAY['Mamoru Oshii'],ARRAY['Production I.G'],ARRAY['Bandai Visual'],
  'Cel animation / Digital (Mixed)','feature film',
  'https://cdn.bottany.app/anime/ghost_in_the_shell.jpg',
  'https://www.ghostintheshell.jp/','https://www.imdb.com/title/tt0113568','https://myanimelist.net/anime/43',
  ARRAY['https://sitgesfilmfestival.com/'],'high'
),
(
  'Perfect Blue','パーフェクトブルー','Perfect Blue | パーフェクトブルー',
  1997,'classic',
  'fantasia','Fantasia Festival — Jury Mention','Best Asian Film','jury','賞 (Award)',
  ARRAY['Satoshi Kon'],ARRAY['Madhouse'],ARRAY['Rex Entertainment'],
  'Cel animation','feature film',
  'https://cdn.bottany.app/anime/perfect_blue.jpg',
  'https://www.madhouse.co.jp/','https://www.imdb.com/title/tt0156887','https://myanimelist.net/anime/437',
  ARRAY['https://fantasiafestival.com/'],'medium'
),
(
  'Princess Mononoke','もののけ姫','Princess Mononoke | もののけ姫',
  1997,'classic',
  'japan_academy_pre','Japan Academy — Special Award','Special Recognition','special','賞 (Award)',
  ARRAY['Hayao Miyazaki'],ARRAY['Studio Ghibli'],ARRAY['Tokuma Shoten'],
  'Cel animation / Digital (Mixed)','feature film',
  'https://cdn.bottany.app/anime/mononoke.jpg',
  'https://www.ghibli.jp/','https://www.imdb.com/title/tt0119698','https://myanimelist.net/anime/164',
  ARRAY['https://www.japan-academy-prize.jp/'],'high'
),
(
  'Grave of the Fireflies','火垂るの墓','Grave of the Fireflies | 火垂るの墓',
  1988,'classic',
  'blue_ribbon','Blue Ribbon Awards — Special Award','Special Award','special','賞 (Award)',
  ARRAY['Isao Takahata'],ARRAY['Studio Ghibli'],ARRAY['Shinchosha'],
  'Cel animation','feature film',
  'https://cdn.bottany.app/anime/fireflies.jpg',
  'https://www.ghibli.jp/','https://www.imdb.com/title/tt0095327','https://myanimelist.net/anime/578',
  ARRAY['https://www.allcinema.net/'],'high'
),
(
  'Angel’s Egg','天使のたまご','Angel’s Egg | 天使のたまご',
  1985,'classic',
  'annecy','Annecy — Jury Mention','Jury Mention','jury','賞 (Award)',
  ARRAY['Mamoru Oshii'],ARRAY['Studio Deen'],ARRAY['Tokuma Shoten'],
  'Cel animation','feature film',
  'https://cdn.bottany.app/anime/angels_egg.jpg',
  'https://www.deen.co.jp/','https://www.imdb.com/title/tt0208502','https://myanimelist.net/anime/885',
  ARRAY['https://www.annecyfestival.com/'],'medium'
),
(
  'Patlabor: The Movie','機動警察パトレイバー','Patlabor: The Movie | 機動警察パトレイバー',
  1989,'classic',
  'mainichi','Mainichi Film Awards — Special Mention','Special Mention','special','賞 (Award)',
  ARRAY['Mamoru Oshii'],ARRAY['Production I.G'],ARRAY['Bandai Visual'],
  'Cel animation','feature film',
  'https://cdn.bottany.app/anime/patlabor.jpg',
  'https://www.production-ig.co.jp/','https://www.imdb.com/title/tt0098062','https://myanimelist.net/anime/1095',
  ARRAY['https://mainichi.jp/'],'medium'
),
(
  'Millennium Actress','千年女優','Millennium Actress | 千年女優',
  2001,'modern',
  'fantasia','Fantasia Festival — Best Animated Film','Best Animated Film','feature','賞 (Award)',
  ARRAY['Satoshi Kon'],ARRAY['Madhouse'],ARRAY['Kadokawa Shoten'],
  'Digital animation','feature film',
  'https://cdn.bottany.app/anime/millennium_actress.jpg',
  'https://www.madhouse.co.jp/','https://www.imdb.com/title/tt0291350','https://myanimelist.net/anime/1033',
  ARRAY['https://fantasiafestival.com/'],'high'
),
(
  'Tokyo Godfathers','東京ゴッドファーザーズ','Tokyo Godfathers | 東京ゴッドファーザーズ',
  2003,'modern',
  'sitges','Sitges — Special Award','Special Award','special','賞 (Award)',
  ARRAY['Satoshi Kon'],ARRAY['Madhouse'],ARRAY['Sony Pictures Japan'],
  'Digital animation','feature film',
  'https://cdn.bottany.app/anime/tokyo_godfathers.jpg',
  'https://www.madhouse.co.jp/','https://www.imdb.com/title/tt0388473','https://myanimelist.net/anime/759',
  ARRAY['https://sitgesfilmfestival.com/'],'high'
),
(
  'Jin-Roh: The Wolf Brigade','人狼','Jin-Roh: The Wolf Brigade | 人狼',
  1999,'classic',
  'fantasia','Fantasia Festival — Jury Award','Best Asian Film','jury','賞 (Award)',
  ARRAY['Hiroyuki Okiura'],ARRAY['Production I.G'],ARRAY['Bandai Visual'],
  'Cel animation / Digital (Mixed)','feature film',
  'https://cdn.bottany.app/anime/jin_roh.jpg',
  'https://www.production-ig.co.jp/','https://www.imdb.com/title/tt0193253','https://myanimelist.net/anime/570',
  ARRAY['https://fantasiafestival.com/'],'high'
),
(
  'Royal Space Force: The Wings of Honneamise','王立宇宙軍 オネアミスの翼','Royal Space Force: The Wings of Honneamise | 王立宇宙軍 オネアミスの翼',
  1987,'classic',
  'annecy','Annecy — Screening','Official Selection','screening','賞 (Award)',
  ARRAY['Hiroyuki Yamaga'],ARRAY['Gainax'],ARRAY['Bandai'],
  'Cel animation','feature film',
  'https://cdn.bottany.app/anime/honneamise.jpg',
  'https://www.gainax.co.jp/','https://www.imdb.com/title/tt0093207','https://myanimelist.net/anime/1034',
  ARRAY['https://www.annecyfestival.com/'],'medium'
),
(
  'My Neighbor Totoro','となりのトトロ','My Neighbor Totoro | となりのトトロ',
  1988,'classic',
  'mainichi','Mainichi Film Awards — Ofuji Award','Ofuji Noburo Award','special','大賞 (Grand Prize)',
  ARRAY['Hayao Miyazaki'],ARRAY['Studio Ghibli'],ARRAY['Tokuma Shoten'],
  'Cel animation','feature film',
  'https://cdn.bottany.app/anime/totoro.jpg',
  'https://www.ghibli.jp/','https://www.imdb.com/title/tt0096283','https://myanimelist.net/anime/523',
  ARRAY['https://mainichi.jp/'],'high'
),
(
  'Kiki’s Delivery Service','魔女の宅急便','Kiki’s Delivery Service | 魔女の宅急便',
  1989,'classic',
  'kinema_junpo','Kinema Junpo Awards — Reader’s Choice','Reader’s Choice','special','賞 (Award)',
  ARRAY['Hayao Miyazaki'],ARRAY['Studio Ghibli'],ARRAY['Tokuma Shoten'],
  'Cel animation','feature film',
  'https://cdn.bottany.app/anime/kiki.jpg',
  'https://www.ghibli.jp/','https://www.imdb.com/title/tt0097814','https://myanimelist.net/anime/512',
  ARRAY['https://www.kinejun.com/'],'high'
),
(
  'Castle in the Sky','天空の城ラピュタ','Laputa: Castle in the Sky | 天空の城ラピュタ',
  1986,'classic',
  'annecy','Annecy — Screening','Official Selection','screening','賞 (Award)',
  ARRAY['Hayao Miyazaki'],ARRAY['Studio Ghibli'],ARRAY['Tokuma Shoten'],
  'Cel animation','feature film',
  'https://cdn.bottany.app/anime/laputa.jpg',
  'https://www.ghibli.jp/','https://www.imdb.com/title/tt0092067','https://myanimelist.net/anime/513',
  ARRAY['https://www.annecyfestival.com/'],'medium'
),
(
  'Porco Rosso','紅の豚','Porco Rosso | 紅の豚',
  1992,'classic',
  'annecy','Annecy — Jury Mention','Jury Mention','jury','賞 (Award)',
  ARRAY['Hayao Miyazaki'],ARRAY['Studio Ghibli'],ARRAY['Tokuma Shoten'],
  'Cel animation','feature film',
  'https://cdn.bottany.app/anime/porco_rosso.jpg',
  'https://www.ghibli.jp/','https://www.imdb.com/title/tt0104652','https://myanimelist.net/anime/416',
  ARRAY['https://www.annecyfestival.com/'],'medium'
),
(
  'Only Yesterday','おもひでぽろぽろ','Only Yesterday | おもひでぽろぽろ',
  1991,'classic',
  'blue_ribbon','Blue Ribbon Awards — Special Award','Special Award','special','賞 (Award)',
  ARRAY['Isao Takahata'],ARRAY['Studio Ghibli'],ARRAY['Tokuma Shoten'],
  'Cel animation','feature film',
  'https://cdn.bottany.app/anime/only_yesterday.jpg',
  'https://www.ghibli.jp/','https://www.imdb.com/title/tt0102587','https://myanimelist.net/anime/1029',
  ARRAY['https://www.allcinema.net/'],'high'
),
(
  'Roujin Z','老人Z','Roujin Z | 老人Z',
  1991,'classic',
  'annecy','Annecy — Screening','Official Selection','screening','賞 (Award)',
  ARRAY['Hiroyuki Kitakubo'],ARRAY['A.P.P.P.'],ARRAY['Sony Music Entertainment Japan'],
  'Cel animation / Digital (Mixed)','feature film',
  'https://cdn.bottany.app/anime/roujin_z.jpg',
  'https://www.app.jp/','https://www.imdb.com/title/tt0102802','https://myanimelist.net/anime/200',
  ARRAY['https://www.annecyfestival.com/'],'medium'
),
(
  'Memories','MEMORIES','Memories | MEMORIES',
  1995,'classic',
  'sitges','Sitges — Special Recognition','Special Recognition','special','賞 (Award)',
  ARRAY['Katsuhiro Otomo'],ARRAY['Madhouse'],ARRAY['Bandai Visual'],
  'Cel animation / Digital (Mixed)','anthology film',
  'https://cdn.bottany.app/anime/memories.jpg',
  'https://www.madhouse.co.jp/','https://www.imdb.com/title/tt0113799','https://myanimelist.net/anime/1462',
  ARRAY['https://sitgesfilmfestival.com/'],'high'
),
(
  'Ninja Scroll','獣兵衛忍風帖','Ninja Scroll | 獣兵衛忍風帖',
  1993,'classic',
  'fantasia','Fantasia Festival — Screening','Official Selection','screening','賞 (Award)',
  ARRAY['Yoshiaki Kawajiri'],ARRAY['Madhouse'],ARRAY['JVC'],
  'Cel animation','feature film',
  'https://cdn.bottany.app/anime/ninja_scroll.jpg',
  'https://www.madhouse.co.jp/','https://www.imdb.com/title/tt0107692','https://myanimelist.net/anime/617',
  ARRAY['https://fantasiafestival.com/'],'medium'
),
(
  'The Castle of Cagliostro','カリオストロの城','The Castle of Cagliostro | カリオストロの城',
  1979,'classic',
  'annecy','Annecy — Screening','Official Selection','screening','賞 (Award)',
  ARRAY['Hayao Miyazaki'],ARRAY['Tokyo Movie Shinsha'],ARRAY['TMS Entertainment'],
  'Cel animation','feature film',
  'https://cdn.bottany.app/anime/cagliostro.jpg',
  'https://www.tms-e.co.jp/','https://www.imdb.com/title/tt0079833','https://myanimelist.net/anime/1430',
  ARRAY['https://www.annecyfestival.com/'],'medium'
),
(
  'Belladonna of Sadness','哀しみのベラドンナ','Belladonna of Sadness | 哀しみのベラドンナ',
  1973,'classic',
  'berlinale','Berlin — Forum Screening','Forum Section','screening','賞 (Award)',
  ARRAY['Eiichi Yamamoto'],ARRAY['Mushi Production'],ARRAY['Osamu Tezuka Productions'],
  'Experimental animation (Mixed)','feature film',
  'https://cdn.bottany.app/anime/belladonna.jpg',
  'https://tezukaosamu.net/','https://www.imdb.com/title/tt0071203','https://myanimelist.net/anime/3220',
  ARRAY['https://www.berlinale.de/'],'medium'
),
(
  'Future Boy Conan','未来少年コナン','Future Boy Conan | 未来少年コナン',
  1978,'classic',
  'annecy','Annecy — Television Screening','TV Selection','screening','賞 (Award)',
  ARRAY['Hayao Miyazaki'],ARRAY['Nippon Animation'],ARRAY['NHK'],
  'Cel animation','TV series',
  'https://cdn.bottany.app/anime/conan.jpg',
  'https://www.nippon-animation.co.jp/','https://www.imdb.com/title/tt0077013','https://myanimelist.net/anime/302',
  ARRAY['https://www.annecyfestival.com/'],'medium'
),
(
  'Space Battleship Yamato','宇宙戦艦ヤマト','Space Battleship Yamato | 宇宙戦艦ヤマト',
  1977,'classic',
  'japan_film_festival','Japan Film Festival — Special Recognition','Cultural Impact','special','賞 (Award)',
  ARRAY['Leiji Matsumoto'],ARRAY['Academy Productions'],ARRAY['Office Academy'],
  'Cel animation','feature film / TV',
  'https://cdn.bottany.app/anime/yamato.jpg',
  'https://yamato2199.net/','https://www.imdb.com/title/tt0078693','https://myanimelist.net/anime/1650',
  ARRAY['https://www.japanesefilmfestival.net/'],'low'
),
(
  'Mobile Suit Gundam','機動戦士ガンダム','Mobile Suit Gundam I | 機動戦士ガンダム',
  1981,'classic',
  'kinema_junpo',$str$Kinema Junpo — Reader's Choice$str$,$str$Reader's Choice$str$,'special','賞 (Award)',
  ARRAY['Yoshiyuki Tomino'],ARRAY['Sunrise'],ARRAY['Sotsu'],
  'Cel animation','compilation film',
  'https://cdn.bottany.app/anime/gundam.jpg',
  'https://www.sunrise-inc.co.jp/','https://www.imdb.com/title/tt0159513','https://myanimelist.net/anime/1090',
  ARRAY['https://www.kinejun.com/'],'medium'
),
(
  'Galaxy Express 999','銀河鉄道999','Galaxy Express 999 | 銀河鉄道999',
  1979,'classic',
  'mainichi','Mainichi Film Awards — Special Award','Special Award','special','賞 (Award)',
  ARRAY['Rintaro'],ARRAY['Toei Animation'],ARRAY['Toei'],
  'Cel animation','feature film',
  'https://cdn.bottany.app/anime/galaxy999.jpg',
  'https://www.toei-anim.co.jp/','https://www.imdb.com/title/tt0079182','https://myanimelist.net/anime/1491',
  ARRAY['https://mainichi.jp/'],'high'
),
(
  'Barefoot Gen','はだしのゲン','Barefoot Gen | はだしのゲン',
  1983,'classic',
  'hiroshima','Hiroshima Animation Festival — Jury Award','Jury Award','jury','賞 (Award)',
  ARRAY['Mori Masaki'],ARRAY['Madhouse'],ARRAY['Gen Production'],
  'Cel animation','feature film',
  'https://cdn.bottany.app/anime/barefoot_gen.jpg',
  'https://www.madhouse.co.jp/','https://www.imdb.com/title/tt0085218','https://myanimelist.net/anime/1824',
  ARRAY['https://hiroanim.org/'],'medium'
),
(
  'Urusei Yatsura: Only You','うる星やつら オンリー・ユー','Urusei Yatsura: Only You | うる星やつら オンリー・ユー',
  1983,'classic',
  'annecy','Annecy — Screening','Official Selection','screening','賞 (Award)',
  ARRAY['Mamoru Oshii'],ARRAY['Studio Pierrot'],ARRAY['Kitty Films'],
  'Cel animation','feature film',
  'https://cdn.bottany.app/anime/urusei.jpg',
  'https://pierrot.jp/','https://www.imdb.com/title/tt0086510','https://myanimelist.net/anime/192',
  ARRAY['https://www.annecyfestival.com/'],'medium'
),
(
  'Doomed Megalopolis','帝都物語','Doomed Megalopolis | 帝都物語',
  1991,'classic',
  'fantasia','Fantasia — Special Recognition','Special Recognition','special','賞 (Award)',
  ARRAY['Rintaro'],ARRAY['Madhouse'],ARRAY['Kadokawa Shoten'],
  'Cel animation / Digital (Mixed)','OVA',
  'https://cdn.bottany.app/anime/teito.jpg',
  'https://www.madhouse.co.jp/','https://www.imdb.com/title/tt0104706','https://myanimelist.net/anime/1148',
  ARRAY['https://fantasiafestival.com/'],'medium'
),
(
  'Metropolis','メトロポリス','Metropolis | メトロポリス',
  2001,'modern',
  'fantasia','Fantasia — Best Animated Film','Best Animated Film','feature','賞 (Award)',
  ARRAY['Rintaro'],ARRAY['Madhouse'],ARRAY['Kadokawa Shoten'],
  'Digital / CGI (Mixed)','feature film',
  'https://cdn.bottany.app/anime/metropolis.jpg',
  'https://www.madhouse.co.jp/','https://www.imdb.com/title/tt0293416','https://myanimelist.net/anime/522',
  ARRAY['https://fantasiafestival.com/'],'high'
),
(
  'Vampire Hunter D','吸血鬼ハンターD','Vampire Hunter D | 吸血鬼ハンターD',
  1985,'classic',
  'fantasia','Fantasia — Screening','Official Selection','screening','賞 (Award)',
  ARRAY['Toyoo Ashida'],ARRAY['Madhouse'],ARRAY['CBS Sony'],
  'Cel animation','OVA',
  'https://cdn.bottany.app/anime/vampire_d.jpg',
  'https://www.madhouse.co.jp/','https://www.imdb.com/title/tt0090248','https://myanimelist.net/anime/543',
  ARRAY['https://fantasiafestival.com/'],'medium'
),
(
  'Wicked City','妖獣都市','Wicked City | 妖獣都市',
  1987,'classic',
  'sitges','Sitges — Special Recognition','Special Recognition','special','賞 (Award)',
  ARRAY['Yoshiaki Kawajiri'],ARRAY['Madhouse'],ARRAY['Japan Home Video'],
  'Cel animation','OVA',
  'https://cdn.bottany.app/anime/wicked_city.jpg',
  'https://www.madhouse.co.jp/','https://www.imdb.com/title/tt0096446','https://myanimelist.net/anime/1107',
  ARRAY['https://sitgesfilmfestival.com/'],'medium'
),
(
  'Golgo 13: The Professional','ゴルゴ13','Golgo 13: The Professional | ゴルゴ13',
  1983,'classic',
  'annecy','Annecy — Screening','Official Selection','screening','賞 (Award)',
  ARRAY['Osamu Dezaki'],ARRAY['Tokyo Movie Shinsha'],ARRAY['TMS'],
  'Cel animation / Early CGI (Mixed)','feature film',
  'https://cdn.bottany.app/anime/golgo13.jpg',
  'https://www.tms-e.co.jp/','https://www.imdb.com/title/tt0086148','https://myanimelist.net/anime/1760',
  ARRAY['https://www.annecyfestival.com/'],'medium'
),
(
  'The Dagger of Kamui','カムイの剣','The Dagger of Kamui | カムイの剣',
  1985,'classic',
  'mainichi','Mainichi — Special Award','Special Award','special','賞 (Award)',
  ARRAY['Rintaro'],ARRAY['Madhouse'],ARRAY['Kadokawa'],
  'Cel animation','feature film',
  'https://cdn.bottany.app/anime/kamui.jpg',
  'https://www.madhouse.co.jp/','https://www.imdb.com/title/tt0091334','https://myanimelist.net/anime/496',
  ARRAY['https://mainichi.jp/'],'medium'
),
(
  'Night on the Galactic Railroad','銀河鉄道の夜','Night on the Galactic Railroad | 銀河鉄道の夜',
  1985,'classic',
  'hiroshima','Hiroshima — Jury Mention','Jury Mention','jury','賞 (Award)',
  ARRAY['Gisaburo Sugii'],ARRAY['Group TAC'],ARRAY['Kadokawa'],
  'Cel animation','feature film',
  'https://cdn.bottany.app/anime/galactic_railroad.jpg',
  'https://www.grouptac.com/','https://www.imdb.com/title/tt0089206','https://myanimelist.net/anime/1441',
  ARRAY['https://hiroanim.org/'],'medium'
)
ON CONFLICT DO NOTHING;


-- -----------------------------------------------------------------------------
-- kitten_pets / kitten_adoptions / kitten_global_events
-- No seed data needed — populated at runtime by bot commands
-- -----------------------------------------------------------------------------


COMMIT;
