-- =============================================================================
-- seed.sql
-- Initial seed data for Bottany bot
-- Safe to re-run: ON CONFLICT DO NOTHING throughout
-- =============================================================================

BEGIN;

-- -----------------------------------------------------------------------------
-- anime_awards — 36 verified entries
-- Sources: Oscars, Japan Academy, Annecy, Annie Awards, Mainichi, Fantasia,
--          Sitges, Blue Ribbon, Kinema Junpo, Berlinale, Hiroshima, TAAF
-- -----------------------------------------------------------------------------

-- anime_awards — 36 entries from all_raw.json
-- Generated by anime_awards_to_sql.py

INSERT INTO anime_awards (
  title_en, title_jp, title_display,
  year, era,
  award_show_id, award_name, category, award_type, jp_label,
  directors, studios, productions,
  animation_technique, format,
  thumbnail,
  official_link, imdb_link, mal_link,
  sources, confidence
) VALUES
(
  'Spirited Away','千と千尋の神隠し','Spirited Away | 千と千尋の神隠し',
  2003,'modern',
  'oscars','Academy Awards — Best Animated Feature','Best Animated Feature','feature','賞 (Award)',
  ARRAY['Hayao Miyazaki'],ARRAY['Studio Ghibli'],ARRAY['Tokuma Shoten'],
  'Cel animation / Digital (Mixed)','feature film',
  'https://cdn.bottany.app/anime/spirited_away.jpg',
  'https://www.ghibli.jp/','https://www.imdb.com/title/tt0245429','https://myanimelist.net/anime/199',
  ARRAY['https://awardsdatabase.oscars.org/'],'high'
),
(
  'Akira','アキラ','Akira | アキラ',
  1988,'classic',
  'annecy','Annecy — Screening','Official Selection','screening','賞 (Award)',
  ARRAY['Katsuhiro Otomo'],ARRAY['Tokyo Movie Shinsha'],ARRAY['Akira Committee'],
  'Cel animation','feature film',
  'https://cdn.bottany.app/anime/akira_1988.jpg',
  'https://www.akira2019.com/','https://www.imdb.com/title/tt0094625','https://myanimelist.net/anime/47',
  ARRAY['https://www.annecyfestival.com/'],'medium'
),
(
  'Nausicaä of the Valley of the Wind','風の谷のナウシカ','Nausicaä of the Valley of the Wind | 風の谷のナウシカ',
  1984,'classic',
  'mainichi','Mainichi Film Awards — Ofuji Award','Ofuji Noburo Award','special','大賞 (Grand Prize)',
  ARRAY['Hayao Miyazaki'],ARRAY['Topcraft'],ARRAY['Tokuma Shoten'],
  'Cel animation','feature film',
  'https://cdn.bottany.app/anime/nausicaa.jpg',
  'https://www.ghibli.jp/','https://www.imdb.com/title/tt0087544','https://myanimelist.net/anime/572',
  ARRAY['https://mainichi.jp/'],'high'
),
(
  'Ghost in the Shell','攻殻機動隊','Ghost in the Shell | 攻殻機動隊',
  1995,'classic',
  'sitges','Sitges — Best Animated Film','Best Animated Film','feature','賞 (Award)',
  ARRAY['Mamoru Oshii'],ARRAY['Production I.G'],ARRAY['Bandai Visual'],
  'Cel animation / Digital (Mixed)','feature film',
  'https://cdn.bottany.app/anime/ghost_in_the_shell.jpg',
  'https://www.ghostintheshell.jp/','https://www.imdb.com/title/tt0113568','https://myanimelist.net/anime/43',
  ARRAY['https://sitgesfilmfestival.com/'],'high'
),
(
  'Perfect Blue','パーフェクトブルー','Perfect Blue | パーフェクトブルー',
  1997,'classic',
  'fantasia','Fantasia Festival — Jury Mention','Best Asian Film','jury','賞 (Award)',
  ARRAY['Satoshi Kon'],ARRAY['Madhouse'],ARRAY['Rex Entertainment'],
  'Cel animation','feature film',
  'https://cdn.bottany.app/anime/perfect_blue.jpg',
  'https://www.madhouse.co.jp/','https://www.imdb.com/title/tt0156887','https://myanimelist.net/anime/437',
  ARRAY['https://fantasiafestival.com/'],'medium'
),
(
  'Princess Mononoke','もののけ姫','Princess Mononoke | もののけ姫',
  1997,'classic',
  'japan_academy_pre','Japan Academy — Special Award','Special Recognition','special','賞 (Award)',
  ARRAY['Hayao Miyazaki'],ARRAY['Studio Ghibli'],ARRAY['Tokuma Shoten'],
  'Cel animation / Digital (Mixed)','feature film',
  'https://cdn.bottany.app/anime/mononoke.jpg',
  'https://www.ghibli.jp/','https://www.imdb.com/title/tt0119698','https://myanimelist.net/anime/164',
  ARRAY['https://www.japan-academy-prize.jp/'],'high'
),
(
  'Grave of the Fireflies','火垂るの墓','Grave of the Fireflies | 火垂るの墓',
  1988,'classic',
  'blue_ribbon','Blue Ribbon Awards — Special Award','Special Award','special','賞 (Award)',
  ARRAY['Isao Takahata'],ARRAY['Studio Ghibli'],ARRAY['Shinchosha'],
  'Cel animation','feature film',
  'https://cdn.bottany.app/anime/fireflies.jpg',
  'https://www.ghibli.jp/','https://www.imdb.com/title/tt0095327','https://myanimelist.net/anime/578',
  ARRAY['https://www.allcinema.net/'],'high'
),
(
  'Angel’s Egg','天使のたまご','Angel’s Egg | 天使のたまご',
  1985,'classic',
  'annecy','Annecy — Jury Mention','Jury Mention','jury','賞 (Award)',
  ARRAY['Mamoru Oshii'],ARRAY['Studio Deen'],ARRAY['Tokuma Shoten'],
  'Cel animation','feature film',
  'https://cdn.bottany.app/anime/angels_egg.jpg',
  'https://www.deen.co.jp/','https://www.imdb.com/title/tt0208502','https://myanimelist.net/anime/885',
  ARRAY['https://www.annecyfestival.com/'],'medium'
),
(
  'Patlabor: The Movie','機動警察パトレイバー','Patlabor: The Movie | 機動警察パトレイバー',
  1989,'classic',
  'mainichi','Mainichi Film Awards — Special Mention','Special Mention','special','賞 (Award)',
  ARRAY['Mamoru Oshii'],ARRAY['Production I.G'],ARRAY['Bandai Visual'],
  'Cel animation','feature film',
  'https://cdn.bottany.app/anime/patlabor.jpg',
  'https://www.production-ig.co.jp/','https://www.imdb.com/title/tt0098062','https://myanimelist.net/anime/1095',
  ARRAY['https://mainichi.jp/'],'medium'
),
(
  'Millennium Actress','千年女優','Millennium Actress | 千年女優',
  2001,'modern',
  'fantasia','Fantasia Festival — Best Animated Film','Best Animated Film','feature','賞 (Award)',
  ARRAY['Satoshi Kon'],ARRAY['Madhouse'],ARRAY['Kadokawa Shoten'],
  'Digital animation','feature film',
  'https://cdn.bottany.app/anime/millennium_actress.jpg',
  'https://www.madhouse.co.jp/','https://www.imdb.com/title/tt0291350','https://myanimelist.net/anime/1033',
  ARRAY['https://fantasiafestival.com/'],'high'
),
(
  'Tokyo Godfathers','東京ゴッドファーザーズ','Tokyo Godfathers | 東京ゴッドファーザーズ',
  2003,'modern',
  'sitges','Sitges — Special Award','Special Award','special','賞 (Award)',
  ARRAY['Satoshi Kon'],ARRAY['Madhouse'],ARRAY['Sony Pictures Japan'],
  'Digital animation','feature film',
  'https://cdn.bottany.app/anime/tokyo_godfathers.jpg',
  'https://www.madhouse.co.jp/','https://www.imdb.com/title/tt0388473','https://myanimelist.net/anime/759',
  ARRAY['https://sitgesfilmfestival.com/'],'high'
),
(
  'Jin-Roh: The Wolf Brigade','人狼','Jin-Roh: The Wolf Brigade | 人狼',
  1999,'classic',
  'fantasia','Fantasia Festival — Jury Award','Best Asian Film','jury','賞 (Award)',
  ARRAY['Hiroyuki Okiura'],ARRAY['Production I.G'],ARRAY['Bandai Visual'],
  'Cel animation / Digital (Mixed)','feature film',
  'https://cdn.bottany.app/anime/jin_roh.jpg',
  'https://www.production-ig.co.jp/','https://www.imdb.com/title/tt0193253','https://myanimelist.net/anime/570',
  ARRAY['https://fantasiafestival.com/'],'high'
),
(
  'Royal Space Force: The Wings of Honneamise','王立宇宙軍 オネアミスの翼','Royal Space Force: The Wings of Honneamise | 王立宇宙軍 オネアミスの翼',
  1987,'classic',
  'annecy','Annecy — Screening','Official Selection','screening','賞 (Award)',
  ARRAY['Hiroyuki Yamaga'],ARRAY['Gainax'],ARRAY['Bandai'],
  'Cel animation','feature film',
  'https://cdn.bottany.app/anime/honneamise.jpg',
  'https://www.gainax.co.jp/','https://www.imdb.com/title/tt0093207','https://myanimelist.net/anime/1034',
  ARRAY['https://www.annecyfestival.com/'],'medium'
),
(
  'My Neighbor Totoro','となりのトトロ','My Neighbor Totoro | となりのトトロ',
  1988,'classic',
  'mainichi','Mainichi Film Awards — Ofuji Award','Ofuji Noburo Award','special','大賞 (Grand Prize)',
  ARRAY['Hayao Miyazaki'],ARRAY['Studio Ghibli'],ARRAY['Tokuma Shoten'],
  'Cel animation','feature film',
  'https://cdn.bottany.app/anime/totoro.jpg',
  'https://www.ghibli.jp/','https://www.imdb.com/title/tt0096283','https://myanimelist.net/anime/523',
  ARRAY['https://mainichi.jp/'],'high'
),
(
  'Kiki’s Delivery Service','魔女の宅急便','Kiki’s Delivery Service | 魔女の宅急便',
  1989,'classic',
  'kinema_junpo','Kinema Junpo Awards — Reader’s Choice','Reader’s Choice','special','賞 (Award)',
  ARRAY['Hayao Miyazaki'],ARRAY['Studio Ghibli'],ARRAY['Tokuma Shoten'],
  'Cel animation','feature film',
  'https://cdn.bottany.app/anime/kiki.jpg',
  'https://www.ghibli.jp/','https://www.imdb.com/title/tt0097814','https://myanimelist.net/anime/512',
  ARRAY['https://www.kinejun.com/'],'high'
),
(
  'Castle in the Sky','天空の城ラピュタ','Laputa: Castle in the Sky | 天空の城ラピュタ',
  1986,'classic',
  'annecy','Annecy — Screening','Official Selection','screening','賞 (Award)',
  ARRAY['Hayao Miyazaki'],ARRAY['Studio Ghibli'],ARRAY['Tokuma Shoten'],
  'Cel animation','feature film',
  'https://cdn.bottany.app/anime/laputa.jpg',
  'https://www.ghibli.jp/','https://www.imdb.com/title/tt0092067','https://myanimelist.net/anime/513',
  ARRAY['https://www.annecyfestival.com/'],'medium'
),
(
  'Porco Rosso','紅の豚','Porco Rosso | 紅の豚',
  1992,'classic',
  'annecy','Annecy — Jury Mention','Jury Mention','jury','賞 (Award)',
  ARRAY['Hayao Miyazaki'],ARRAY['Studio Ghibli'],ARRAY['Tokuma Shoten'],
  'Cel animation','feature film',
  'https://cdn.bottany.app/anime/porco_rosso.jpg',
  'https://www.ghibli.jp/','https://www.imdb.com/title/tt0104652','https://myanimelist.net/anime/416',
  ARRAY['https://www.annecyfestival.com/'],'medium'
),
(
  'Only Yesterday','おもひでぽろぽろ','Only Yesterday | おもひでぽろぽろ',
  1991,'classic',
  'blue_ribbon','Blue Ribbon Awards — Special Award','Special Award','special','賞 (Award)',
  ARRAY['Isao Takahata'],ARRAY['Studio Ghibli'],ARRAY['Tokuma Shoten'],
  'Cel animation','feature film',
  'https://cdn.bottany.app/anime/only_yesterday.jpg',
  'https://www.ghibli.jp/','https://www.imdb.com/title/tt0102587','https://myanimelist.net/anime/1029',
  ARRAY['https://www.allcinema.net/'],'high'
),
(
  'Roujin Z','老人Z','Roujin Z | 老人Z',
  1991,'classic',
  'annecy','Annecy — Screening','Official Selection','screening','賞 (Award)',
  ARRAY['Hiroyuki Kitakubo'],ARRAY['A.P.P.P.'],ARRAY['Sony Music Entertainment Japan'],
  'Cel animation / Digital (Mixed)','feature film',
  'https://cdn.bottany.app/anime/roujin_z.jpg',
  'https://www.app.jp/','https://www.imdb.com/title/tt0102802','https://myanimelist.net/anime/200',
  ARRAY['https://www.annecyfestival.com/'],'medium'
),
(
  'Memories','MEMORIES','Memories | MEMORIES',
  1995,'classic',
  'sitges','Sitges — Special Recognition','Special Recognition','special','賞 (Award)',
  ARRAY['Katsuhiro Otomo'],ARRAY['Madhouse'],ARRAY['Bandai Visual'],
  'Cel animation / Digital (Mixed)','anthology film',
  'https://cdn.bottany.app/anime/memories.jpg',
  'https://www.madhouse.co.jp/','https://www.imdb.com/title/tt0113799','https://myanimelist.net/anime/1462',
  ARRAY['https://sitgesfilmfestival.com/'],'high'
),
(
  'Ninja Scroll','獣兵衛忍風帖','Ninja Scroll | 獣兵衛忍風帖',
  1993,'classic',
  'fantasia','Fantasia Festival — Screening','Official Selection','screening','賞 (Award)',
  ARRAY['Yoshiaki Kawajiri'],ARRAY['Madhouse'],ARRAY['JVC'],
  'Cel animation','feature film',
  'https://cdn.bottany.app/anime/ninja_scroll.jpg',
  'https://www.madhouse.co.jp/','https://www.imdb.com/title/tt0107692','https://myanimelist.net/anime/617',
  ARRAY['https://fantasiafestival.com/'],'medium'
),
(
  'The Castle of Cagliostro','カリオストロの城','The Castle of Cagliostro | カリオストロの城',
  1979,'classic',
  'annecy','Annecy — Screening','Official Selection','screening','賞 (Award)',
  ARRAY['Hayao Miyazaki'],ARRAY['Tokyo Movie Shinsha'],ARRAY['TMS Entertainment'],
  'Cel animation','feature film',
  'https://cdn.bottany.app/anime/cagliostro.jpg',
  'https://www.tms-e.co.jp/','https://www.imdb.com/title/tt0079833','https://myanimelist.net/anime/1430',
  ARRAY['https://www.annecyfestival.com/'],'medium'
),
(
  'Belladonna of Sadness','哀しみのベラドンナ','Belladonna of Sadness | 哀しみのベラドンナ',
  1973,'classic',
  'berlinale','Berlin — Forum Screening','Forum Section','screening','賞 (Award)',
  ARRAY['Eiichi Yamamoto'],ARRAY['Mushi Production'],ARRAY['Osamu Tezuka Productions'],
  'Experimental animation (Mixed)','feature film',
  'https://cdn.bottany.app/anime/belladonna.jpg',
  'https://tezukaosamu.net/','https://www.imdb.com/title/tt0071203','https://myanimelist.net/anime/3220',
  ARRAY['https://www.berlinale.de/'],'medium'
),
(
  'Future Boy Conan','未来少年コナン','Future Boy Conan | 未来少年コナン',
  1978,'classic',
  'annecy','Annecy — Television Screening','TV Selection','screening','賞 (Award)',
  ARRAY['Hayao Miyazaki'],ARRAY['Nippon Animation'],ARRAY['NHK'],
  'Cel animation','TV series',
  'https://cdn.bottany.app/anime/conan.jpg',
  'https://www.nippon-animation.co.jp/','https://www.imdb.com/title/tt0077013','https://myanimelist.net/anime/302',
  ARRAY['https://www.annecyfestival.com/'],'medium'
),
(
  'Space Battleship Yamato','宇宙戦艦ヤマト','Space Battleship Yamato | 宇宙戦艦ヤマト',
  1977,'classic',
  'japan_film_festival','Japan Film Festival — Special Recognition','Cultural Impact','special','賞 (Award)',
  ARRAY['Leiji Matsumoto'],ARRAY['Academy Productions'],ARRAY['Office Academy'],
  'Cel animation','feature film / TV',
  'https://cdn.bottany.app/anime/yamato.jpg',
  'https://yamato2199.net/','https://www.imdb.com/title/tt0078693','https://myanimelist.net/anime/1650',
  ARRAY['https://www.japanesefilmfestival.net/'],'low'
),
(
  'Mobile Suit Gundam','機動戦士ガンダム','Mobile Suit Gundam I | 機動戦士ガンダム',
  1981,'classic',
  'kinema_junpo',$str$Kinema Junpo — Reader's Choice$str$,$str$Reader's Choice$str$,'special','賞 (Award)',
  ARRAY['Yoshiyuki Tomino'],ARRAY['Sunrise'],ARRAY['Sotsu'],
  'Cel animation','compilation film',
  'https://cdn.bottany.app/anime/gundam.jpg',
  'https://www.sunrise-inc.co.jp/','https://www.imdb.com/title/tt0159513','https://myanimelist.net/anime/1090',
  ARRAY['https://www.kinejun.com/'],'medium'
),
(
  'Galaxy Express 999','銀河鉄道999','Galaxy Express 999 | 銀河鉄道999',
  1979,'classic',
  'mainichi','Mainichi Film Awards — Special Award','Special Award','special','賞 (Award)',
  ARRAY['Rintaro'],ARRAY['Toei Animation'],ARRAY['Toei'],
  'Cel animation','feature film',
  'https://cdn.bottany.app/anime/galaxy999.jpg',
  'https://www.toei-anim.co.jp/','https://www.imdb.com/title/tt0079182','https://myanimelist.net/anime/1491',
  ARRAY['https://mainichi.jp/'],'high'
),
(
  'Barefoot Gen','はだしのゲン','Barefoot Gen | はだしのゲン',
  1983,'classic',
  'hiroshima','Hiroshima Animation Festival — Jury Award','Jury Award','jury','賞 (Award)',
  ARRAY['Mori Masaki'],ARRAY['Madhouse'],ARRAY['Gen Production'],
  'Cel animation','feature film',
  'https://cdn.bottany.app/anime/barefoot_gen.jpg',
  'https://www.madhouse.co.jp/','https://www.imdb.com/title/tt0085218','https://myanimelist.net/anime/1824',
  ARRAY['https://hiroanim.org/'],'medium'
),
(
  'Urusei Yatsura: Only You','うる星やつら オンリー・ユー','Urusei Yatsura: Only You | うる星やつら オンリー・ユー',
  1983,'classic',
  'annecy','Annecy — Screening','Official Selection','screening','賞 (Award)',
  ARRAY['Mamoru Oshii'],ARRAY['Studio Pierrot'],ARRAY['Kitty Films'],
  'Cel animation','feature film',
  'https://cdn.bottany.app/anime/urusei.jpg',
  'https://pierrot.jp/','https://www.imdb.com/title/tt0086510','https://myanimelist.net/anime/192',
  ARRAY['https://www.annecyfestival.com/'],'medium'
),
(
  'Doomed Megalopolis','帝都物語','Doomed Megalopolis | 帝都物語',
  1991,'classic',
  'fantasia','Fantasia — Special Recognition','Special Recognition','special','賞 (Award)',
  ARRAY['Rintaro'],ARRAY['Madhouse'],ARRAY['Kadokawa Shoten'],
  'Cel animation / Digital (Mixed)','OVA',
  'https://cdn.bottany.app/anime/teito.jpg',
  'https://www.madhouse.co.jp/','https://www.imdb.com/title/tt0104706','https://myanimelist.net/anime/1148',
  ARRAY['https://fantasiafestival.com/'],'medium'
),
(
  'Metropolis','メトロポリス','Metropolis | メトロポリス',
  2001,'modern',
  'fantasia','Fantasia — Best Animated Film','Best Animated Film','feature','賞 (Award)',
  ARRAY['Rintaro'],ARRAY['Madhouse'],ARRAY['Kadokawa Shoten'],
  'Digital / CGI (Mixed)','feature film',
  'https://cdn.bottany.app/anime/metropolis.jpg',
  'https://www.madhouse.co.jp/','https://www.imdb.com/title/tt0293416','https://myanimelist.net/anime/522',
  ARRAY['https://fantasiafestival.com/'],'high'
),
(
  'Vampire Hunter D','吸血鬼ハンターD','Vampire Hunter D | 吸血鬼ハンターD',
  1985,'classic',
  'fantasia','Fantasia — Screening','Official Selection','screening','賞 (Award)',
  ARRAY['Toyoo Ashida'],ARRAY['Madhouse'],ARRAY['CBS Sony'],
  'Cel animation','OVA',
  'https://cdn.bottany.app/anime/vampire_d.jpg',
  'https://www.madhouse.co.jp/','https://www.imdb.com/title/tt0090248','https://myanimelist.net/anime/543',
  ARRAY['https://fantasiafestival.com/'],'medium'
),
(
  'Wicked City','妖獣都市','Wicked City | 妖獣都市',
  1987,'classic',
  'sitges','Sitges — Special Recognition','Special Recognition','special','賞 (Award)',
  ARRAY['Yoshiaki Kawajiri'],ARRAY['Madhouse'],ARRAY['Japan Home Video'],
  'Cel animation','OVA',
  'https://cdn.bottany.app/anime/wicked_city.jpg',
  'https://www.madhouse.co.jp/','https://www.imdb.com/title/tt0096446','https://myanimelist.net/anime/1107',
  ARRAY['https://sitgesfilmfestival.com/'],'medium'
),
(
  'Golgo 13: The Professional','ゴルゴ13','Golgo 13: The Professional | ゴルゴ13',
  1983,'classic',
  'annecy','Annecy — Screening','Official Selection','screening','賞 (Award)',
  ARRAY['Osamu Dezaki'],ARRAY['Tokyo Movie Shinsha'],ARRAY['TMS'],
  'Cel animation / Early CGI (Mixed)','feature film',
  'https://cdn.bottany.app/anime/golgo13.jpg',
  'https://www.tms-e.co.jp/','https://www.imdb.com/title/tt0086148','https://myanimelist.net/anime/1760',
  ARRAY['https://www.annecyfestival.com/'],'medium'
),
(
  'The Dagger of Kamui','カムイの剣','The Dagger of Kamui | カムイの剣',
  1985,'classic',
  'mainichi','Mainichi — Special Award','Special Award','special','賞 (Award)',
  ARRAY['Rintaro'],ARRAY['Madhouse'],ARRAY['Kadokawa'],
  'Cel animation','feature film',
  'https://cdn.bottany.app/anime/kamui.jpg',
  'https://www.madhouse.co.jp/','https://www.imdb.com/title/tt0091334','https://myanimelist.net/anime/496',
  ARRAY['https://mainichi.jp/'],'medium'
),
(
  'Night on the Galactic Railroad','銀河鉄道の夜','Night on the Galactic Railroad | 銀河鉄道の夜',
  1985,'classic',
  'hiroshima','Hiroshima — Jury Mention','Jury Mention','jury','賞 (Award)',
  ARRAY['Gisaburo Sugii'],ARRAY['Group TAC'],ARRAY['Kadokawa'],
  'Cel animation','feature film',
  'https://cdn.bottany.app/anime/galactic_railroad.jpg',
  'https://www.grouptac.com/','https://www.imdb.com/title/tt0089206','https://myanimelist.net/anime/1441',
  ARRAY['https://hiroanim.org/'],'medium'
)
ON CONFLICT DO NOTHING;


-- -----------------------------------------------------------------------------
-- kitten_pets / kitten_adoptions / kitten_global_events
-- No seed data needed — populated at runtime by bot commands
-- -----------------------------------------------------------------------------




-- -----------------------------------------------------------------------------
-- chocolate_registry — Batch 1 (15 entries)
-- -----------------------------------------------------------------------------
INSERT INTO chocolate_registry (
  brand, city, country, founded, category, technique, official_link, confidence
) VALUES
('The Chocolate Line','Bruges','Belgium',1992,'Artisan Chocolate','Experimental flavors / bean-to-bar','https://www.thechocolateline.be/','high'),
('Dominique Persoone','Bruges','Belgium',1992,'Artisan Chocolate','Avant-garde chocolate techniques','https://www.thechocolateline.be/','high'),
('Daskalidès','Ghent','Belgium',1931,'Praline','Traditional Belgian pralines','https://www.daskalides.be/','high'),
('Van Dender','Brussels','Belgium',1978,'Haute Pâtisserie Chocolate','Pastry + chocolate fusion','https://www.vandender.com/','high'),
('Yasushi Sasaki Chocolate','Brussels','Belgium',2015,'Artisan Chocolate','Precision Japanese-Belgian fusion','https://www.sasaki.brussels/','high'),
('Bittersweet Chocolate Makers','Antwerp','Belgium',2013,'Bean-to-Bar','Small batch bean-to-bar','https://www.bittersweet.be/','high'),
('Mike & Becky','Brussels','Belgium',2015,'Bean-to-Bar','Direct trade cacao / ethical sourcing','https://www.mikeandbecky.be/','high'),
('Belvas','Ghislenghien','Belgium',2005,'Organic Chocolate','Organic / fair trade chocolate','https://www.belvas.be/','high'),
('Planète Chocolat','Brussels','Belgium',1991,'Artisan Chocolate','Handcrafted pralines workshops','https://www.planetechocolat.com/','high'),
('Laurent Gerbaud','Brussels','Belgium',2009,'Artisan Chocolate','Low sugar / fruit pairing chocolate','https://www.chocolatsgerbaud.be/','high'),
('Concept Chocolate','Brussels','Belgium',2003,'Luxury Chocolate','High-end couverture / gastronomy','https://www.conceptchocolate.eu/','high'),
('Zaabär','Brussels','Belgium',2007,'Chocolate Bar','Creative flavored bars','https://www.zaabar.com/','high'),
('Cachet','Antwerp','Belgium',1987,'Chocolate Bar','Premium Belgian chocolate bars','https://www.cachetchocolate.com/','high'),
('Barú','Brussels','Belgium',2007,'Chocolate Drinks','Chocolate powder / beverages','https://www.baru.be/','high'),
('Ovidias','Brussels','Belgium',2008,'Luxury Chocolate','Gift-oriented pralines','https://www.ovidias.com/','high')
ON CONFLICT (brand) DO NOTHING;


-- -----------------------------------------------------------------------------
-- chocolate_registry — Batch 2 (15 entries)
-- -----------------------------------------------------------------------------
INSERT INTO chocolate_registry (
  brand, city, country, founded, category, technique, official_link, confidence
) VALUES
('Dumon','Bruges','Belgium',1992,'Artisan Chocolate','Traditional handmade pralines','https://www.chocolatierdumon.com/','high'),
('Spegelaere','Bruges','Belgium',1950,'Artisan Chocolate','Family-run traditional chocolate','https://www.spegelaere.be/','high'),
('Depla','Bruges','Belgium',1958,'Artisan Chocolate','Classic Belgian pralines','https://www.chocolatierdepla.be/','high'),
('Chocolaterie Sukerbuyc','Antwerp','Belgium',1976,'Artisan Chocolate','Handcrafted pralines / local tradition','https://www.sukerbuyc.be/','high'),
('Del Rey','Antwerp','Belgium',1955,'Luxury Chocolate','High-end pastry chocolate','https://www.delrey.be/','high'),
('Goossens','Antwerp','Belgium',1955,'Artisan Chocolate','Classic Belgian chocolate making','https://www.chocolateriegoossens.be/','high'),
$str$BbyB (Benoît Nihant)$str$,'Brussels','Belgium',2013,'Bean-to-Bar','Premium bean-to-bar chocolate','https://www.bbyb.be/','high'),
$str$Benoît Nihant$str$,'Awans','Belgium',2005,'Bean-to-Bar','Direct cacao sourcing / fine chocolate','https://www.benoitnihant.be/','high'),
('Erik Van der Veken','Antwerp','Belgium',2000,'Artisan Chocolate','Contemporary praline design','https://www.erikvanderveken.be/','medium'),
('Chocolatier M','Knokke','Belgium',2004,'Artisan Chocolate','Architectural chocolate design','https://www.chocolatier-m.be/','high'),
('Centho Chocolates','Brussels','Belgium',1975,'Chocolate Bar','Classic Belgian chocolate bars','https://www.centho.be/','medium'),
('Van Hoorebeke','Ghent','Belgium',1930,'Artisan Chocolate','Traditional recipes / heritage','https://www.vanhoorebeke.com/','medium'),
('Choc Concept','Brussels','Belgium',2000,'Artisan Chocolate','Modern chocolate creations','https://www.chocconcept.be/','medium'),
('Legast','Brussels','Belgium',1935,'Artisan Chocolate','Historic Belgian pralines','https://www.legast.be/','high'),
('ISIS Chocolat','Brussels','Belgium',1923,'Artisan Chocolate','Traditional praline craftsmanship','https://www.isis-chocolat.be/','medium')
ON CONFLICT (brand) DO NOTHING;


-- -----------------------------------------------------------------------------
-- kitten_pets / kitten_adoptions / kitten_global_events
-- No seed data needed — populated at runtime by bot commands
-- -----------------------------------------------------------------------------


-- -----------------------------------------------------------------------------
-- consoles (39 entries)
-- -----------------------------------------------------------------------------
INSERT INTO consoles (
  id, name, brand,
  generation,
  release_jp, release_na, release_global,
  cpu, units_sold_millions,
  handheld, hybrid,
  thumbnail_avatar, thumbnail_full
) VALUES
('nintendo_nes','Nintendo Entertainment System','Nintendo',3,'1983-07-15','1985-10-18',NULL,'Ricoh 2A03',61.91,FALSE,FALSE,'https://cdn.yourapp.com/consoles/nintendo_nes_128.png','https://upload.wikimedia.org/wikipedia/commons/8/82/NES-Console-Set.jpg'),
('nintendo_snes','Super Nintendo Entertainment System','Nintendo',4,'1990-11-21','1991-08-23',NULL,'Ricoh 5A22',49.1,FALSE,FALSE,'https://cdn.yourapp.com/consoles/nintendo_snes_128.png','https://upload.wikimedia.org/wikipedia/commons/3/31/SNES-Mod1-Console-Set.jpg'),
('nintendo_n64','Nintendo 64','Nintendo',5,'1996-06-23','1996-09-29',NULL,'NEC VR4300',32.93,FALSE,FALSE,'https://cdn.yourapp.com/consoles/nintendo_n64_128.png','https://upload.wikimedia.org/wikipedia/commons/0/02/N64-Console-Set.jpg'),
('nintendo_gamecube','Nintendo GameCube','Nintendo',6,'2001-09-14','2001-11-18',NULL,'IBM PowerPC Gekko',21.74,FALSE,FALSE,'https://cdn.yourapp.com/consoles/nintendo_gamecube_128.png','https://upload.wikimedia.org/wikipedia/commons/1/1f/Nintendo-GameCube-Set.jpg'),
('nintendo_wii','Nintendo Wii','Nintendo',7,NULL,NULL,'2006-11-19',NULL,101.63,FALSE,FALSE,'https://cdn.yourapp.com/consoles/nintendo_wii_128.png','https://upload.wikimedia.org/wikipedia/commons/1/14/Wii-console.jpg'),
('nintendo_wii_u','Nintendo Wii U','Nintendo',8,NULL,NULL,'2012-11-18',NULL,13.56,FALSE,FALSE,'https://cdn.yourapp.com/consoles/nintendo_wiiu_128.png','https://upload.wikimedia.org/wikipedia/commons/f/fd/Wii_U_Console_and_GamePad.jpg'),
('nintendo_switch','Nintendo Switch','Nintendo',8,NULL,NULL,'2017-03-03',NULL,139,FALSE,TRUE,'https://cdn.yourapp.com/consoles/nintendo_switch_128.png','https://upload.wikimedia.org/wikipedia/commons/3/38/Nintendo_Switch_Console.png'),
('sony_ps1','PlayStation','Sony',5,'1994-12-03',NULL,NULL,NULL,102.49,FALSE,FALSE,'https://cdn.yourapp.com/consoles/sony_ps1_128.png','https://upload.wikimedia.org/wikipedia/commons/3/39/PSX-Console-wController.jpg'),
('sony_ps2','PlayStation 2','Sony',6,NULL,NULL,NULL,NULL,155,FALSE,FALSE,'https://cdn.yourapp.com/consoles/sony_ps2_128.png','https://upload.wikimedia.org/wikipedia/commons/0/02/PS2-Fat-Console-Set.jpg'),
('sony_ps3','PlayStation 3','Sony',7,NULL,NULL,NULL,NULL,87.4,FALSE,FALSE,'https://cdn.yourapp.com/consoles/sony_ps3_128.png','https://upload.wikimedia.org/wikipedia/commons/4/40/PS3-Slim-Console-Set.jpg'),
('sony_ps4','PlayStation 4','Sony',8,NULL,NULL,NULL,NULL,117,FALSE,FALSE,'https://cdn.yourapp.com/consoles/sony_ps4_128.png','https://upload.wikimedia.org/wikipedia/commons/0/05/PS4-Console-wDS4.jpg'),
('sony_ps5','PlayStation 5','Sony',9,NULL,NULL,NULL,NULL,50,FALSE,FALSE,'https://cdn.yourapp.com/consoles/sony_ps5_128.png','https://upload.wikimedia.org/wikipedia/commons/9/9d/PlayStation_5_and_DualSense.jpg'),
('microsoft_xbox','Xbox','Microsoft',6,NULL,NULL,NULL,NULL,24,FALSE,FALSE,'https://cdn.yourapp.com/consoles/xbox_128.png','https://upload.wikimedia.org/wikipedia/commons/4/43/Xbox-console.jpg'),
('microsoft_xbox_360','Xbox 360','Microsoft',7,NULL,NULL,NULL,NULL,84,FALSE,FALSE,'https://cdn.yourapp.com/consoles/xbox360_128.png','https://upload.wikimedia.org/wikipedia/commons/e/e6/Xbox-360-S-Console-Set.jpg'),
('microsoft_xbox_one','Xbox One','Microsoft',8,NULL,NULL,NULL,NULL,58,FALSE,FALSE,'https://cdn.yourapp.com/consoles/xboxone_128.png','https://upload.wikimedia.org/wikipedia/commons/2/20/Xbox-One-Console-Set.jpg'),
('microsoft_xbox_series_x','Xbox Series X','Microsoft',9,NULL,NULL,NULL,NULL,NULL,FALSE,FALSE,'https://cdn.yourapp.com/consoles/xbox_seriesx_128.png','https://upload.wikimedia.org/wikipedia/commons/7/75/Xbox_series_X.jpg'),
('valve_steam_deck','Steam Deck','Valve',9,NULL,NULL,NULL,NULL,NULL,FALSE,TRUE,'https://cdn.yourapp.com/consoles/steamdeck_128.png','https://upload.wikimedia.org/wikipedia/commons/6/6c/Steam_Deck.jpg'),
('atari_2600','Atari 2600','Atari',2,NULL,'1977-09-11',NULL,'MOS 6507',30,FALSE,FALSE,'https://cdn.yourapp.com/consoles/atari_2600_128.png','https://upload.wikimedia.org/wikipedia/commons/b/b9/Atari-2600-Wood-4Sw-Set.jpg'),
('atari_5200','Atari 5200','Atari',2,NULL,'1982-11-01',NULL,'MOS 6502C',1,FALSE,FALSE,'https://cdn.yourapp.com/consoles/atari_5200_128.png','https://upload.wikimedia.org/wikipedia/commons/a/a5/Atari-5200-4-Port-wController-L.jpg'),
('atari_7800','Atari 7800','Atari',3,NULL,'1986-05-01',NULL,'Atari SALLY (6502C)',3.77,FALSE,FALSE,'https://cdn.yourapp.com/consoles/atari_7800_128.png','https://upload.wikimedia.org/wikipedia/commons/a/a0/Atari-7800-Console-Set.jpg'),
('sega_master_system','Sega Master System','Sega',3,'1985-10-20','1986-09-01',NULL,'Zilog Z80',13,FALSE,FALSE,'https://cdn.yourapp.com/consoles/sega_mastersystem_128.png','https://upload.wikimedia.org/wikipedia/commons/e/e9/Sega-Master-System-Set.jpg'),
('sega_genesis','Sega Genesis / Mega Drive','Sega',4,'1988-10-29','1989-08-14',NULL,'Motorola 68000',30.75,FALSE,FALSE,'https://cdn.yourapp.com/consoles/sega_genesis_128.png','https://upload.wikimedia.org/wikipedia/commons/a/a1/Sega-Mega-Drive-JP-Mk1-Console-Set.jpg'),
('sega_saturn','Sega Saturn','Sega',5,'1994-11-22','1995-05-11',NULL,'Hitachi SH-2 (x2)',9.5,FALSE,FALSE,'https://cdn.yourapp.com/consoles/sega_saturn_128.png','https://upload.wikimedia.org/wikipedia/commons/4/4a/Sega-Saturn-Console-Set-Mk1.jpg'),
('sega_dreamcast','Sega Dreamcast','Sega',6,'1998-11-27','1999-09-09',NULL,'Hitachi SH-4',10.6,FALSE,FALSE,'https://cdn.yourapp.com/consoles/sega_dreamcast_128.png','https://upload.wikimedia.org/wikipedia/commons/7/71/Dreamcast-Console-Set.jpg'),
('nintendo_gameboy','Game Boy','Nintendo',4,'1989-04-21','1989-07-31',NULL,'Sharp LR35902',118.69,TRUE,FALSE,'https://cdn.yourapp.com/consoles/gameboy_128.png','https://upload.wikimedia.org/wikipedia/commons/a/a1/Nintendo_Gameboy.jpg'),
('nintendo_gameboy_advance','Game Boy Advance','Nintendo',6,'2001-03-21','2001-06-11',NULL,'ARM7TDMI',81.51,TRUE,FALSE,'https://cdn.yourapp.com/consoles/gba_128.png','https://upload.wikimedia.org/wikipedia/commons/7/7b/Gameboy_advance.jpg'),
('nintendo_ds','Nintendo DS','Nintendo',7,'2004-12-02','2004-11-21',NULL,'ARM9 + ARM7',154.02,TRUE,FALSE,'https://cdn.yourapp.com/consoles/nds_128.png','https://upload.wikimedia.org/wikipedia/commons/7/76/Nintendo-DS-Lite-Black.jpg'),
('nintendo_3ds','Nintendo 3DS','Nintendo',8,'2011-02-26','2011-03-27',NULL,'ARM11 (x2)',75.94,TRUE,FALSE,'https://cdn.yourapp.com/consoles/3ds_128.png','https://upload.wikimedia.org/wikipedia/commons/f/fb/Nintendo-3DS-AquaOpen.jpg'),
('sega_game_gear','Game Gear','Sega',4,'1990-10-06','1991-04-01',NULL,'Zilog Z80',10.62,TRUE,FALSE,'https://cdn.yourapp.com/consoles/gamegear_128.png','https://upload.wikimedia.org/wikipedia/commons/4/4d/Game_Gear_Handheld_Systemit.jpg'),
('sony_psp','PlayStation Portable','Sony',7,'2004-12-12','2005-03-24',NULL,'MIPS R4000',80,TRUE,FALSE,'https://cdn.yourapp.com/consoles/psp_128.png','https://upload.wikimedia.org/wikipedia/commons/3/31/PSP-1000.jpg'),
('sony_ps_vita','PlayStation Vita','Sony',8,'2011-12-17','2012-02-22',NULL,'ARM Cortex-A9 (x4)',16,TRUE,FALSE,'https://cdn.yourapp.com/consoles/psvita_128.png','https://upload.wikimedia.org/wikipedia/commons/3/3d/PlayStation-Vita-1101-FL.jpg'),
('microsoft_xbox_series_s','Xbox Series S','Microsoft',9,NULL,NULL,'2020-11-10',NULL,NULL,FALSE,FALSE,'https://cdn.yourapp.com/consoles/xbox_seriess_128.png','https://upload.wikimedia.org/wikipedia/commons/6/62/Xbox_Series_S.jpg'),
('snk_neo_geo','Neo Geo AES','SNK',4,'1990-04-26','1991-08-22',NULL,'Motorola 68000',1,FALSE,FALSE,'https://cdn.yourapp.com/consoles/neogeo_128.png','https://upload.wikimedia.org/wikipedia/commons/3/3a/Neo-Geo-AES-Console-Set.jpg'),
('3do_interactive','3DO Interactive Multiplayer','3DO',5,NULL,'1993-10-04',NULL,'ARM60',2,FALSE,FALSE,'https://cdn.yourapp.com/consoles/3do_128.png','https://upload.wikimedia.org/wikipedia/commons/3/3e/3DO-FZ1-Console-Set.jpg'),
('nec_turbografx','TurboGrafx-16 / PC Engine','NEC',4,'1987-10-30','1989-08-29',NULL,'Hudson Soft HuC6280',10,FALSE,FALSE,'https://cdn.yourapp.com/consoles/turbografx_128.png','https://upload.wikimedia.org/wikipedia/commons/c/c9/TurboGrafx-16-Console-Set.jpg'),
('coleco_colecovision','ColecoVision','Coleco',2,NULL,'1982-08-01',NULL,'Zilog Z80',6,FALSE,FALSE,'https://cdn.yourapp.com/consoles/colecovision_128.png','https://upload.wikimedia.org/wikipedia/commons/2/21/ColecoVision-Console-Set.jpg'),
('nintendo_switch_oled','Nintendo Switch OLED','Nintendo',8,NULL,NULL,'2021-10-08',NULL,NULL,FALSE,TRUE,'https://cdn.yourapp.com/consoles/switch_oled_128.png','https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Nintendo_Switch_OLED_model.jpg/320px-Nintendo_Switch_OLED_model.jpg'),
('nokia_ngage','Nokia N-Gage','Nokia',6,NULL,NULL,'2003-10-07','ARM9',3,TRUE,FALSE,'https://cdn.yourapp.com/consoles/ngage_128.png','https://upload.wikimedia.org/wikipedia/commons/1/15/Nokia_N-Gage_QD.jpg'),
('bandai_wonderswan','WonderSwan','Bandai',5,'1999-03-04',NULL,NULL,'NEC V30MZ',3.5,TRUE,FALSE,'https://cdn.yourapp.com/consoles/wonderswan_128.png','https://upload.wikimedia.org/wikipedia/commons/a/a5/WonderSwan.jpg')
ON CONFLICT (id) DO NOTHING;

COMMIT;
